export const SOME_ACTION = "SOME_ACTION";
export const INIT_SOME_ACTION = "INIT_SOME_ACTION";


export const ROOT_ACTION = "ROOT_ACTION";

// ** Json Forms ** 
export const INIT_JSON_FORM = "INIT_JSON_FORM";

// ** Object Manager ** 
export const INIT_OBJECT_MANAGER = "INIT_OBJECT_MANAGER"
export const OPEN_ITEM_IN_OBJECT_MANAGER = "OPEN_ITEM_IN_OBJECT_MANAGER"
export const FETCH_OBJECT_MANAGER_ITEM = "FETCH_OBJECT_MANAGER_ITEM"
export const ADD_OBJECT_MANAGER_ITEM = "ADD_OBJECT_MANAGER_ITEM"
export const CLOSE_OBJECT_MANAGER_ITEM = "CLOSE_OBJECT_MANAGER_ITEM"
export const SET_OBJECT_MANAGER_ITEM_DATA = "SET_OBJECT_MANAGER_ITEM_DATA"
export const UPDATE_OBJECT_MANAGER_ITEM_DATA = "UPDATE_OBJECT_MANAGER_ITEM_DATA"
